# Generated by Django 4.1 on 2024-07-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_pickupmodel_is_full_alter_goodsmodel_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupmodel',
            name='is_full',
        ),
    ]
