# Generated by Django 4.1 on 2024-07-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_goodsmodel_price_alter_ordermodel_total_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentofgoodsmodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsmodel',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratingofgoodsmodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
