# Generated by Django 4.1 on 2024-07-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_commentofgoodsmodel_time_goodsmodel_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentofgoodsmodel',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ratingofgoodsmodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
