# Generated by Django 4.1 on 2024-07-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_commentofgoodsmodel_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentofgoodsmodel',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
