# Generated by Django 4.1 on 2024-07-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_commentofgoodsmodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentofgoodsmodel',
            name='t_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
