# Generated by Django 4.1 on 2024-07-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_rename_time_commentofgoodsmodel_time_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingofgoodsmodel',
            name='time_r',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentofgoodsmodel',
            name='time_comment',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
