# Generated by Django 4.1 on 2024-07-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TegsOfGoodsModel',
        ),
    ]
