# Generated by Django 4.1 on 2024-07-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_goodsmodel_ordermodel_pickupmodel_tegsofgoodsmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='time_of_pick_up',
        ),
    ]
