# Generated by Django 4.1 on 2024-07-03 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_ordermodel_time_of_pick_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePickUpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_pick_up', models.DateField()),
                ('time_of_pick_up', models.CharField(choices=[('9.00-10.00', '9.00-10.00'), ('10.00-11.00', '10.00-11.00'), ('11.00-12.00', '11.00-12.00'), ('12.00-13.00', '12.00-13.00'), ('13.00-14.00', '13.00-14.00'), ('14.00-15.00', '14.00-15.00'), ('15.00-16.00', '15.00-16.00'), ('16.00-17.00', '16.00-17.00'), ('17.00-18.00', '17.00-18.00')], max_length=100)),
                ('count', models.IntegerField(default=5)),
                ('pick_up_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.pickupmodel')),
            ],
        ),
    ]
