# Generated by Django 4.1 on 2024-07-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='time_of_pick_up',
            field=models.CharField(choices=[('9.00-10.00', '9.00-10.00'), ('10.00-11.00', '10.00-11.00'), ('11.00-12.00', '11.00-12.00'), ('12.00-13.00', '12.00-13.00'), ('13.00-14.00', '13.00-14.00'), ('14.00-15.00', '14.00-15.00'), ('15.00-16.00', '15.00-16.00'), ('16.00-17.00', '16.00-17.00'), ('17.00-18.00', '17.00-18.00')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
