# Generated by Django 4.1 on 2024-07-09 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_goodsmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmodel',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.subcategorymodel'),
            preserve_default=False,
        ),
    ]
