# Generated by Django 4.1 on 2024-07-09 17:39

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_choicecategorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicecategorymodel',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='id_parent', on_delete=django.db.models.deletion.CASCADE, to='shop.subcategorymodel'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='id_parent', on_delete=django.db.models.deletion.CASCADE, to='shop.subcategorymodel'),
        ),
    ]
