# Generated by Django 4.1 on 2024-07-09 18:20

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_choicecategorymodel_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupmodel',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.categorymodel'),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='id_parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.subcategorymodel'),
        ),
        migrations.DeleteModel(
            name='ChoiceCategoryModel',
        ),
    ]
