# Generated by Django 4.1 on 2024-07-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_pickupmodel_is_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupmodel',
            name='adres',
            field=models.CharField(max_length=50),
        ),
    ]
