# Generated by Django 4.1 on 2024-07-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_pickupmodel_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='total_money',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='price_one',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
