# Generated by Django 4.1 on 2024-07-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_commentofgoodsmodel_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentofgoodsmodel',
            old_name='t_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='ratingofgoodsmodel',
            name='t_time',
        ),
        migrations.AlterField(
            model_name='ratingofgoodsmodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
