# Generated by Django 4.1 on 2024-07-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_rename_t_time_commentofgoodsmodel_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentofgoodsmodel',
            old_name='time',
            new_name='time_comment',
        ),
        migrations.RenameField(
            model_name='ratingofgoodsmodel',
            old_name='time',
            new_name='time_rating',
        ),
    ]
