# Generated by Django 4.1 on 2024-07-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_ratingofgoodsmodel_time_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingofgoodsmodel',
            old_name='time_r',
            new_name='time_rating',
        ),
    ]
