FROM python:3.10


ENV VAR1=10
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code

# Install python dependencies in /.venv
COPY Pipfile Pipfile.lock ./
RUN python -m pip install --upgrade pip
RUN pip install pipenv 

COPY . /code
RUN pipenv install && bash -c pipenv run python manage.py migrate && bash -c pipenv run seed all

# COPY . /code

RUN chmod a+x /code/entrypoint.sh
ENTRYPOINT ["/bin/sh", "/code/entrypoint.sh"]
# ENTRYPOINT ["/bin/sh", "-c", "tail -f /dev/null"]

