# Generated by Django 4.1 on 2024-08-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_goodsmodel_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.subcategorymodel'),
        ),
    ]
