# Generated by Django 4.1 on 2024-07-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_privatecontentcategory_delete_timepickupmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateContentCategory',
        ),
    ]
