# Generated by Django 4.1 on 2024-07-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_categorymodel_remove_goodsmodel_id_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.categorymodel'),
            preserve_default=False,
        ),
    ]
