# Generated by Django 4.1 on 2024-07-10 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_commentofgoodsmodel_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentofgoodsmodel',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
