# Generated by Django 4.1 on 2024-07-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_commentofgoodsmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentofgoodsmodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
