# Generated by Django 4.1 on 2024-07-10 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_commentofgoodsmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentofgoodsmodel',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ratingofgoodsmodel',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
