# Generated by Django 4.1 on 2024-07-13 09:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_rename_time_r_ratingofgoodsmodel_time_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategorymodel',
            options={'verbose_name_plural': 'subcategories'},
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goodsmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.categorymodel'),
        ),
        migrations.AlterField(
            model_name='ratingofgoodsmodel',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
