# Generated by Django 4.1 on 2024-08-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_delete_tegsofgoodsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={},
        ),
    ]
